In [ ]:
import cv2
import numpy as np

In [2]:
def is_empty(any_structure):
    if any_structure:
        print('Structure is not empty.')
        return False
    else:
        print('Structure is empty.')
        return True

In [ ]:
region = 0
init = cv2.imread(r'C:\Users\ICON\Desktop\FYP\Images\face.jpg')
image = cv2.cvtColor(init, cv2.COLOR_BGR2GRAY)
blank_image = 255*np.ones((512,512,3), np.uint8)
#cv2.imshow("Eyes",image)
#image = cv2.VideoCapture(0)
#image=img.read()
eye_cascade = cv2.CascadeClassifier(r'C:\Users\ICON\Desktop\FYP\haarcascade\haarcascade_eye_tree_eyeglasses.xml')
nose_classifier = cv2.CascadeClassifier(r'C:\Users\ICON\Desktop\FYP\haarcascade\haarcascade_mcs_nose.xml')
mouth_classifier = cv2.CascadeClassifier(r'C:\Users\ICON\Desktop\FYP\haarcascade\haarcascade_mcs_mouth.xml')
eyes = eye_cascade.detectMultiScale(image,scaleFactor = 3, minNeighbors=6)
mouth = mouth_classifier.detectMultiScale(image,scaleFactor = 5, minNeighbors=6)
nose = nose_classifier.detectMultiScale(image,scaleFactor = 3, minNeighbors=6)
print(eyes)
print(mouth)
print(nose)
sum=0

try:
    if is_empty(eyes):
        print("Eyes Not Found")
except:
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(image, (ex, ey), (ex + ew, ey + eh), (255, 255, 0), 2)
        sum=sum+ex
        print(ex)
    crop_img = image[ey:ey+eh,int((sum-ex)/2):sum]
    cv2.imshow("cropped",crop_img)
    cv2.waitKey(0)
    # roi = cv2.selectROI(region)
    # print(roi)
    # imcropped = image[int(roi[1]):int(roi[1]+roi[3]),
    #                 int(roi[0]):int(roi[0]+roi[2])]
    # cv2.imshow("output", imcropped)
    # cv2.waitKey(0)

try:
    if is_empty(mouth):
        print("Mouth Not Found")
except:
    for (mx, my, mw, mh) in mouth:
        cv2.rectangle(image, (mx, my), (mx + mw, my + mh), (0, 0, 0), 2)
        #cv2.rectangle(image, (ex, ey), (ex + ew, ey + eh), (255, 255, 0), 2)
try:
    if is_empty(nose):
        print("Nose Not Found")
except:
    for (nx, ny, nw, nh) in nose:
        cv2.rectangle(image, (nx, ny), (nx + nw, ny + nh), (0, 0, 255), 2)
        #cv2.rectangle(image, (ex, ey), (ex + ew, ey + eh), (255, 255, 0), 2)

#cv2.imshow("Eyes",image)
cv2.waitKey(0)

[[119 179  60  60]
 [226 171  60  60]]
[[145 295 125  75]]
[[174 246  54  45]]
119
226


In [ ]:
print("fadadss")

In [ ]:
print("fadsdas")